<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframetiny-react_7076801221704788373610_ifr</name>
   <tag></tag>
   <elementGuidId>42c86fef-3093-4118-bf9e-0b4d6986e9e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tiny-react_7076801221704788373610_ifr']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'tiny-react_7076801221704788373610_ifr' and @title = 'Rich Text Area']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tiny-react_7076801221704788373610_ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>794e43a2-93d6-4f52-898d-aa3c3a713f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiny-react_7076801221704788373610_ifr</value>
      <webElementGuid>f8a33382-baa9-4be7-aed8-5c1463e98520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>42f9cfff-c6ab-46e3-b077-71668d405cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3357083a-99d6-4dec-a234-e2d5baefbaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>3ce7f826-2f53-4686-821a-c856ec2dcb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>9ba459b9-b919-4097-bed0-f095a7829ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcdoc</name>
      <type>Main</type>
      <value>&lt;!DOCTYPE html>&lt;html>&lt;head>&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; />&lt;/head>&lt;body id=&quot;tinymce&quot; class=&quot;mce-content-body &quot; data-id=&quot;tiny-react_7076801221704788373610&quot; aria-label=&quot;Rich Text Area. Press ALT-0 for help.&quot;>&lt;br>&lt;/body>&lt;/html></value>
      <webElementGuid>922a7179-f8c3-4342-a567-ee34b5837da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiny-react_7076801221704788373610_ifr&quot;)</value>
      <webElementGuid>9c9150b3-74d5-415d-b59f-5d8296e8d24d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tiny-react_7076801221704788373610_ifr']</value>
      <webElementGuid>ece46cf6-8528-4da1-9170-ec5270aff94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/main/div/div/div/div[3]/div/div[2]/div/div/div/div/div/div[2]/div/iframe</value>
      <webElementGuid>75fe5101-4040-4d19-b50b-beb8885b8634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>39908f87-2229-43ca-b6d3-bfb7892c8707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tiny-react_7076801221704788373610_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>2b21ff70-2232-49bd-8279-5d4f89320c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
