<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__ProseMirror ProseMirror-example-setup-_4bc0b4</name>
   <tag></tag>
   <elementGuidId>a28fe0da-1e40-49d1-b9f1-10d4b3700f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ProseMirror.ProseMirror-example-setup-style.ProseMirror-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='editor']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Like this oneTry it out by typing in here or see more examples.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd6dfb9b-53b9-478b-b180-ead2dc4430bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21e0bd73-44c7-4459-bf4f-35b545c59b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7c36cc6f-dd6b-4915-a0d7-6fd78b93495a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProseMirror ProseMirror-example-setup-style ProseMirror-focused</value>
      <webElementGuid>44f709f2-6466-429a-97e3-1d7542cab63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editor&quot;)/div[@class=&quot;ProseMirror-menubar-wrapper&quot;]/div[@class=&quot;ProseMirror ProseMirror-example-setup-style ProseMirror-focused&quot;]</value>
      <webElementGuid>6c565009-2b4c-4ed5-bc6b-918381406f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editor']/div/div[2]</value>
      <webElementGuid>997c4d00-a5b2-4616-80cd-2bce0f58cc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⬚'])[1]/following::div[1]</value>
      <webElementGuid>8a520e57-c620-4f5d-bccc-4476b693caee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type...'])[1]/following::div[9]</value>
      <webElementGuid>ec83b806-6558-46ef-af08-649e0e19dfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='examples'])[2]/preceding::div[1]</value>
      <webElementGuid>60156f5c-44c4-4e48-baff-fec15ed5d169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>0edba23d-c13d-46d9-bd4c-a2b096691555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
