<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_New Contact</name>
   <tag></tag>
   <elementGuidId>ee33cd2d-7d0c-47a8-a06b-504e028d1671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.slds-modal__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper-body']/header/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;New Contact&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6febed7a-fb68-4368-be0b-00c25d96ca8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-modal__title</value>
      <webElementGuid>772c7119-097c-4954-aa48-7acad4ea2567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2381:0</value>
      <webElementGuid>b00d7225-5552-450e-907b-ec47b39ea61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Contact</value>
      <webElementGuid>5aea9847-dd86-4519-ab54-9b1753ffae08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper-body&quot;)/header[@class=&quot;slds-modal__header&quot;]/h2[@class=&quot;slds-modal__title&quot;]</value>
      <webElementGuid>54b2d443-2d32-4648-b413-4d78c7ca1fb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-body']/header/h2</value>
      <webElementGuid>aa2a4802-8b77-41e3-b9d0-3bb62b31ace0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close this window'])[1]/following::h2[1]</value>
      <webElementGuid>c94f966d-0ab6-44eb-9b32-1f3ce919b26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[2]/following::h2[1]</value>
      <webElementGuid>77ecda56-f2d2-4290-bbd4-53c7dc582a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::h2[1]</value>
      <webElementGuid>f58acb9a-6507-4611-aa85-e49ed85410e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; New'])[1]/preceding::h2[1]</value>
      <webElementGuid>dd86330e-7a15-4835-8662-42eb3c7b8ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/h2</value>
      <webElementGuid>291b91c3-1738-4904-9804-139352b1c154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'New Contact' or . = 'New Contact')]</value>
      <webElementGuid>14df9fc5-ba03-484e-b491-c44bf6693301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
