<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suffix_suffix</name>
   <tag></tag>
   <elementGuidId>798b1f6c-f866-4e05-a4a2-2f6d19489747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-860</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-860']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Suffix&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09407efb-4fc5-455b-8477-983c35cdb179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>93cfc407-39f3-4702-ba7e-cac09c3102bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-860</value>
      <webElementGuid>973272d3-e7bf-43c3-a7e8-6b0eb8b0a831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-860</value>
      <webElementGuid>1df8a9ba-2076-4a5e-817b-21e905fb070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>a2b1344e-2c46-4d79-9ce5-525830250c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>suffix</value>
      <webElementGuid>3941461c-39fc-4bc4-a7f5-c0cc9bdd8688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb87c258-1e0c-4d4b-99ba-a18a23248360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Suffix</value>
      <webElementGuid>dca441d6-628d-4f7c-8147-460a559a47fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5da7a6f-9731-4136-85dc-2dd732fc1f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-860&quot;)</value>
      <webElementGuid>301b3dc6-b413-4272-80d6-1c14726a0727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-860']</value>
      <webElementGuid>91d26584-53d9-4a92-85c8-834b4dcf1fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-843']/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-input-name/lightning-input-name/fieldset/div/div/div[5]/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>cfd368c7-3d28-4f2f-882c-ea24e68e9172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>2e524e9a-6a75-40d3-89d3-baca8cc61a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-860' and @name = 'suffix' and @placeholder = 'Suffix' and @type = 'text']</value>
      <webElementGuid>1544b211-0365-4d9c-ba53-fdce2cacb187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
