<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Increased</name>
   <tag></tag>
   <elementGuidId>fa8cbcb3-eac8-4060-85c1-8ab1a74196af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div[2]/runtime_pipeline_inspector-kpi-panel/div/div[4]/button/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Increased&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2e0dfbab-ddc2-49ad-9a56-a66aed106253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-text-align--left slds-text-body_small kpiName flexItem</value>
      <webElementGuid>e2e84da9-2d97-4868-892a-6d98bd65bb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Increased</value>
      <webElementGuid>88662cb6-55c9-4826-83e6-74ef2389d3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;container slds-grid slds-grid_vertical runtime_pipeline_inspectorPipelineInspectorHome&quot;]/div[@class=&quot;mainContainer slds-is-relative slds-col slds-grid&quot;]/div[@class=&quot;mainContainerChild slds-col slds-grid slds-grid_vertical&quot;]/div[@class=&quot;slds-theme_inverse mainContainerHeader&quot;]/runtime_pipeline_inspector-kpi-panel[@class=&quot;runtime_pipeline_inspectorKpiPanelWrapper&quot;]/div[@class=&quot;slds-theme_inverse slds-grid blueBottomBorder kpiElementsWrapper&quot;]/div[@class=&quot;slds-is-relative kpiButtonContainer&quot;]/button[@class=&quot;slds-p-around_none slds-m-horizontal--x-small slds-m-vertical--none kpiButton&quot;]/div[@class=&quot;slds-p-vertical_small slds-p-horizontal_small slds-m-vertical_none slds-text-color_inverse slds-text-heading_xsmall slds-theme_inverse kpiElementDiv inactive&quot;]/div[@class=&quot;slds-grid&quot;]/p[@class=&quot;slds-text-align--left slds-text-body_small kpiName flexItem&quot;]</value>
      <webElementGuid>525b017e-bc9f-4878-9a09-3433d000fa44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div[2]/runtime_pipeline_inspector-kpi-panel/div/div[4]/button/div/div/p</value>
      <webElementGuid>f3c93a78-252b-46e2-aff9-5daa49d1a3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a few seconds ago'])[1]/following::p[7]</value>
      <webElementGuid>43353d87-dffc-44c2-8129-fca1929e0aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount:'])[1]/preceding::p[2]</value>
      <webElementGuid>54b68fda-3a59-45e4-ab6a-c61b55df79a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/preceding::p[2]</value>
      <webElementGuid>f20b2cc7-4490-48a4-bdb6-786a9066cde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Increased']/parent::*</value>
      <webElementGuid>05a936ac-66a8-422d-80d8-2708d70586a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/div/div/p</value>
      <webElementGuid>4b77b18a-b5df-45fd-9538-bcb93e2b4106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Increased' or . = 'Increased')]</value>
      <webElementGuid>ea0897e6-7cb3-4fee-a2cf-3da06ef85272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
