<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Won</name>
   <tag></tag>
   <elementGuidId>5aa606d4-4db2-4f4f-b535-dc40943f85a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div[2]/runtime_pipeline_inspector-kpi-panel/div/div[3]/button/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Won&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9d2e20aa-776e-481e-8a7f-f416f408ded5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-text-align--left slds-text-body_small kpiName flexItem</value>
      <webElementGuid>a4c80569-fa8b-426b-a48c-0212310a5fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Won</value>
      <webElementGuid>09e3f164-42ff-4194-9eb8-38cc60e22919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;container slds-grid slds-grid_vertical runtime_pipeline_inspectorPipelineInspectorHome&quot;]/div[@class=&quot;mainContainer slds-is-relative slds-col slds-grid&quot;]/div[@class=&quot;mainContainerChild slds-col slds-grid slds-grid_vertical&quot;]/div[@class=&quot;slds-theme_inverse mainContainerHeader&quot;]/runtime_pipeline_inspector-kpi-panel[@class=&quot;runtime_pipeline_inspectorKpiPanelWrapper&quot;]/div[@class=&quot;slds-theme_inverse slds-grid blueBottomBorder kpiElementsWrapper&quot;]/div[@class=&quot;slds-is-relative kpiButtonContainer&quot;]/button[@class=&quot;slds-p-around_none slds-m-horizontal--x-small slds-m-vertical--none kpiButton&quot;]/div[@class=&quot;slds-p-vertical_small slds-p-horizontal_small slds-m-vertical_none slds-text-color_inverse slds-text-heading_xsmall slds-theme_inverse kpiElementDiv inactive&quot;]/div[@class=&quot;slds-grid&quot;]/p[@class=&quot;slds-text-align--left slds-text-body_small kpiName flexItem&quot;]</value>
      <webElementGuid>304fe16a-eedc-42fe-a600-c90e3300db8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div[2]/runtime_pipeline_inspector-kpi-panel/div/div[3]/button/div/div/p</value>
      <webElementGuid>67a8d48f-4c83-4ccf-9a6b-61d117a18bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a few seconds ago'])[1]/following::p[5]</value>
      <webElementGuid>462b0e20-3155-4a3c-b165-b4087931c7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount:'])[1]/preceding::p[2]</value>
      <webElementGuid>e39b50ae-8d0b-4f52-b29f-f6c3f8b57d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/preceding::p[2]</value>
      <webElementGuid>2792d6aa-5a1e-43e9-b2a6-ac10847d5bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Won']/parent::*</value>
      <webElementGuid>e029c682-fbf5-4901-a83c-ac72bc9a0590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/div/div/p</value>
      <webElementGuid>b5d2f5a5-9325-46cf-9576-606fcf16a688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Won' or . = 'Won')]</value>
      <webElementGuid>17030b08-547c-4988-922e-fbcc71ca1e94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
